import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { CustomMenu } from "@/components/custom/CustomMenu";
import { LateralBar } from "@/components/custom/LateralBar";
import { DraggableRegion } from "@/components/custom/DraggableRegion";

import { cn } from "@/lib/utils";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className="rounded-3xl overflow-hidden"
        >
            <head />
            <DraggableRegion>
                <body
                    className={cn(
                        "min-h-screen font-sans antialiased dark bg-transparent",
                        fontSans.variable,
                    )}
                >
                    <div>
                        <LateralBar />
                    </div>
                    <div className="bg-background relative rounded-3xl">
                        <CustomMenu />
                        {children}
                    </div>
                </body>
            </DraggableRegion>
        </html>
    );
}
